services:
  client:
    build: .
    container_name: financfy_backend
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    restart: on-failure

  database:
    image: postgres:alpine
    container_name: financfy_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - financfydata:/var/lib/postgresql/data/
    restart: on-failure

  migrate:
    image: migrate/migrate
    container_name: financfy_migrator
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "/bin/sh", "-c",
      "migrate -path=/migrations/ -database postgres://adiba:8552@database:5432/financfy_db?sslmode=disable up"
    ]
    depends_on:
      - database

volumes:
  financfydata:
